apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hasty-challenge-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: hasty-challange-manager
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 100